---
name: PR Build

on:
  pull_request:
    branches:
      - master

jobs:
  docker:
    timeout-minutes: 30
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1
  
      - name: Start Containers
        env:
          RAILS_ENV: "production"
        run: docker-compose -f "docker-compose.yml" up --build -d
  
      - name: Stop Containers
        if: always()
        run: docker-compose -f "docker-compose.yml" down
