---
name: Production Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  docker:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    name: "Build"

    steps:
      - name: Checkout
        uses: actions/checkout@v1
        
      - name: Build Container
        run: docker build -t weby .

      - name: Start database container
        run: docker run --name webydb -d --rm --env POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} -v="${PWD}/data:/var/lib/postgresql/data" -v="${PWD}/postgres_init/:/docker-entrypoint-initdb.d/" postgres

      - name: Start weby container
        run: docker run --name weby --link webydb -d --rm --env PG_DB=weby --env PG_USER=postgres --env PG_PASS=${{ secrets.POSTGRES_PASSWORD }} --env PG_HOST=webydb --env SECRET_KEY_BASE=${{ secrets.SECRET_KEY_BASE }} weby

      - name: Precompile assets
        env:
          STORAGE_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY_ID }}
          STORAGE_ACCESS_SECRET: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          STORAGE_BUCKET: ${{ secrets.STORAGE_BUCKET }}
          STORAGE_HOST: ${{ secrets.storage_HOST }}
          RAILS_ENV: production
        run: docker exec --env RAILS_ENV="${{ env.RAILS_ENV }}" --env FOG_PROVIDER="AWS" --env STORAGE_ACCESS_KEY="${{ env.STORAGE_ACCESS_KEY }}" --env STORAGE_ACCESS_SECRET="${{ env.STORAGE_ACCESS_SECRET }}" --env STORAGE_BUCKET="${{ env.STORAGE_BUCKET }}" --env STORAGE_HOST="${{ env.STORAGE_HOST }}" weby bundle exec rake assets:precompile --trace

      - name: Stop database container
        if: always()
        run: docker stop webydb

      - name: Stop weby container
        if: always()
        run: docker stop weby

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Get image version
        id: docker-image-version
        run: |
                echo "::set-output name=image-version::${docker image inspect --format='{{ index .Config.Labels "com.weby.version" }}' weby}"

      - name: Tag Container
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: weby
          IMAGE_TAG: ${{ steps.docker-image-version.outputs.image-version }}
        run: docker tag weby $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Push Container
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: weby
          IMAGE_TAG: ${{ steps.docker-image-version.outputs.image-version }}
        run: docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Tag Container
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: weby
          IMAGE_TAG: latest
        run: docker tag weby $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Push Container
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: weby
          IMAGE_TAG: latest
        run: docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

  terraform:
    name: "Deploy"
    timeout-minutes: 45
    runs-on: ubuntu-latest
    needs: docker

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.15.4
  
      - name: Terraform Init
        run: terraform -chdir=terraform/ init
        env:
         AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
         AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  
      - name: Terraform Format
        run: terraform -chdir=terraform/ fmt -check
  
      - name: Terraform Plan
        run: terraform -chdir=terraform/ plan
        env:
         AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
         AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  
      - name: Terraform Apply
        run: terraform -chdir=terraform/ apply -auto-approve -var=image_tag=${{ steps.docker-image-version.outputs.image-version }}
        env:
         AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
         AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
